version: "3"
services:
    client:
        build: /client/.
        ports:
            - "3000:3000"
        volumes:
            - .:/healthy-living-client
        environment:
            NODE_ENV: development
    server:
        image: webapp-api
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            [webappnetwork]
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork
networks:        
    webappnetwork:
        driver: bridge